import os
import json
from openai import OpenAI
from dotenv import load_dotenv
from csv_visualizer.core.logger import get_logger
logger = get_logger("router")
load_dotenv()


client = OpenAI(
    api_key=os.getenv("API_KEY"),
    base_url=os.getenv("BASE_URL", "https://api.cerebras.ai/v1")
)

MODEL = os.getenv("INTENT_MODEL", "llama3.1-8b")
FALLBACK_MODEL = "llama3.1-8b"

TOOLS = [
{
"type": "function",
"function": {
"name": "planner_tool",
"description": "Create or structurally change a visualization schema",
"parameters": {
"type": "object",
"properties": {
"query": {
"type": "string",
"description": "User visualization request"
}
},
"required": ["query"]
}
}
},
{
"type": "function",
"function": {
"name": "codegen_tool",
"description": "Generate Highcharts code from a schema",
"parameters": {
"type": "object",
"properties": {
"schema": {
"type": "object",
"description": "Visualization schema generated by planner"
}
},
"required": ["schema"]
}
}
},
{
"type": "function",
"function": {
"name": "patch_tool",
"description": "Modify an existing chart (styling, labels, legend, reference lines)",
"parameters": {
"type": "object",
"properties": {
"query": {
"type": "string",
"description": "User modification request"
}
},
"required": ["query"]
}
}
}
]


SYSTEM_PROMPT = """
You are a visualization router.

Your job is to decide which tool should handle the request.

planner_tool
Use when the user:
• creates a new chart
• changes chart type
• changes axes
• changes data columns
• changes aggregation
• restructures the visualization

patch_tool
Use when the user modifies styling or configuration of the existing chart:
• color changes
• legend changes
• label changes
• axis styling
• reference lines
• annotations

Examples:

Create a bar chart of sales by region
→ planner_tool

Convert this chart to scatter plot
→ planner_tool

Plot sepal length vs petal length
→ planner_tool

Change bar color to red
→ patch_tool

Move legend to bottom
→ patch_tool

Add a horizontal line at the mean
→ patch_tool

Always call exactly one tool.
Do not answer with text.
"""


def route_query(state):
    query = state["query"]
    schema = state.get("schema")
    files = state.get("files")

    context = {
        "query": query,
        "has_schema": schema is not None,
        "has_chart_files": files is not None,
    }

    logger.info(f"Query: {query}")

    response = client.chat.completions.create(
        model=MODEL,
        temperature=0,
        timeout=30,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": json.dumps(context)},
        ],
        tools=TOOLS,
        tool_choice="auto",
    )

    message = response.choices[0].message

    if message.tool_calls:
        tool_call = message.tool_calls[0]
        tool_name = tool_call.function.name
        args = tool_call.function.arguments
        if isinstance(args, str):
            args = json.loads(args)
    elif message.content:
        # llama3.1-8b returns JSON in content instead of tool_calls
        try:
            parsed = json.loads(message.content.strip())
            tool_name = parsed.get("name") or parsed.get("tool") or parsed.get("function")
            args = parsed.get("arguments") or parsed.get("args") or {}
            if not tool_name:
                raise ValueError("No tool name in content JSON")
        except Exception:
            raise ValueError(f"Router LLM returned no tool call and unparseable content: {message.content}")
    else:
        raise ValueError("Router LLM returned empty response")

    logger.info(f"Tool selected: {tool_name}")
    return {"tool": tool_name, "args": args}